server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/inventory
    username: root
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
