apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service
  labels:
    app: billing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      containers:
        - name: billing-service
          image: billing-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: admin123
            - name: MYSQL_DB
              value: inventory
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq
            - name: PRECIO_UNITARIO
              value: "25.0"
            - name: CENTRAL_URL
              value: http://central-service:8080/cosechas
---
apiVersion: v1
kind: Service
metadata:
  name: billing-service
spec:
  selector:
    app: billing-service
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
